remote_theme: pages-themes/cayman@v0.2.0
title: "Seño Bluemel Spanish 1"
description: "Seño Bluemel, M.S. Curriculum & Instruction | Championing Global Proficiency and Cultural Inclusivity"

# This hides the 'View on GitHub' and 'Maintained by' section
github:
  is_project_page: false

# This tells GitHub not to look for download links
show_downloads: false

# This links your name in the header to your YouTube channel
header_pages:
  - name: "Seño Bluemel ¡Qué Chévere!"
    url: "https://www.youtube.com/channel/UCvfq1AXJiDzXMV4VlA9ve_w?view_as=subscriber"
